spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 30
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_URL}:${DB_PORT}/PORTFOLIO
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cache:
    cache-names: presigned
    caffeine:
      spec: expireAfterWrite=50m

# 로컬 파일 저장소 설정 (운영)
file:
  storage:
    location: ${FILE_STORAGE_LOCATION:/home/awdesign/uploads}
    base-url: ${FILE_STORAGE_BASE_URL:https://alwaysdesign-portfolio.com/files}

logging:
  file:
    name: /home/awdesign/logs/spring.log
    level:
      root: INFO
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

cookie:
  secure: true

cors:
  url: https://alwaysdesign-portfolio.com

server:
  address: 127.0.0.1
